database:
  username: "TESTUSER"
  password: "testpassword"
  host: "localhost"
  port: 1521
  service: "FREEPDB1"

export:
  schema: "TESTUSER"
  output_dir: "./export_final"
  parallel: 10
  enable_row_hash: false

bigquery:
  project: "pakunuru-1119-20250930202256"
  dataset: "TESTUSER"
